### ISSUE TITLE
Validate action output.needs

### ISSUE THREAD

**Issue by romasku** [neuro-inc/neuro-flow#162]
In action files, user specifies tasks that will be used to compute output in the following way:
```
...
outputs:
  needs: [task_1, task_2]
...
```
Currently those values are not validated and can cause an error during batch execution. Example bad config:
```
kind: batch

outputs:
  needs: [ task_2_bad_suffix ]
  output_var:
    value: ${{ needs.task_2.outputs.output_var }}

tasks:
  - id: task_1
    image: ubuntu
    bash: echo test
  - id: task_2
    image: ubuntu
    bash: echo ::set-output name=output_var::test
```
