### ISSUE TITLE
Validate for incomplete `include` in matrix

### ISSUE THREAD

**Issue by romasku** [neuro-inc/neuro-flow#210]
The following task specification:
```
id: ${{ matrix.param1 }}_${{ matrix.param2 }}
strategy:
  matrix:
    param1: [a, b]
    param2: [x, y]
    include: 
      - param1: a # No value for param2
```
Will cause error during bake execution. It is better to validate for such errors early.
