### ISSUE TITLE
Parse job/task hostnames in flows

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/neuro-flow#232]
I guess the easiest way to describe what I'm talking about is through the use-case description:

We defined two actions in neuro-flow.
One is a web-server (or MLFlow server in my case) which depends on some backend service defined as the second action (PostgreSQL DB server in my case).
The web-server needs to know the host-name of the backend server, which, in turn, depends on the job name, username, cluster name and cannot be hard-coded.

It would be great if we could use some placeholders like `${{ jobs.<job_name>.http_url }}` and `${{ jobs.<job_name>.internal_hostname }}`, which will be rendered by neuro-flow when the job starts:

```yaml
jobs:
  postgres:
    image: postgres:12.5
    name: $[[ flow.title ]]-postgres
    ...

  mlflow_server:
    ...
    cmd: |
      server --host 0.0.0.0
        --backend-store-uri=postgresql://postgres:password@startup-package-test-postgres--yevheniisemendiak.platform-jobs:5432 <- ugly
        --backend-store-uri=postgresql://postgres:password@${{ jobs.postgres.internal_hostname }}:5432  <- looks better
        --default-artifact-root=${{ volumes.mlflow_artifacts.mount }}
```

What do you think?
