### ISSUE TITLE
Boolean input values are not supported in actions

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/neuro-flow#265]
Use-case:
You have an action where one of the inputs is boolean and used to parameterize a job (any bool parameter, for instance, http_auth):
```yaml
inputs:
  http_auth: "False"
job:
  image: myimage
  http_auth: ${{ inputs.http_auth }}
  cmd: |
    echo Hi!
```

If you either host this action in GH ([example](https://github.com/neuro-actions/webdav_server/blob/master/action.yaml#L11)) or store it locally, the only way to get the "False" behavior, is to set this input to `""`.

Otherwise, neuro-flow will:
- raise an exception `ERROR: str is expected, got <class 'bool'>` if you set the input to pure `False`
- convert the value to True, if you set it to anything else, except `""`, (e.g., "False" will be converted to True).

To reproduce it - try to launch [this](https://github.com/neuro-actions/webdav_server) action with a disabled auth.
