### ISSUE TITLE
Support neuro config's information inside yaml config

### ISSUE THREAD

**Issue by atemate** [neuro-inc/neuro-flow#275]
Use-case:
```

  postgres:
    image: postgres:12.5
    name: $[[ flow.title ]]-postgres
    http_port: 5432
    http_auth: False
    life_span: 30d
    detach: True
    volumes:
      - ${{ volumes.postgress_storage.remote }}:/var/lib/postgresql/data:rw
    env:
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: ""
      PGDATA: /var/lib/postgresql/data/pgdata

  mlflow_server:
    image: neuromation/mlflow:1.11.0
    name: $[[ flow.title ]]-mlflow-server
    http_port: 5000
    http_auth: False
    life_span: 30d
    detach: True
    volumes:
      - ${{ volumes.mlflow_artifacts.ref_rw }}
    cmd: |
      export NEURO_USER=artemyushkovskiy  # I wish this could be not hard-coded: `${{ neuro_config.user }}`
      server --host 0.0.0.0
        --backend-store-uri=postgresql://postgres:password@ml-recipe-bone-age-postgres--${NEURO_USER}.platform-jobs:5432
        --default-artifact-root=${{ volumes.mlflow_artifacts.mount }}
```
SOmething like `${{ neuro_config.user }}` would really help
