### ISSUE TITLE
Error is raised in case if unoppened template is found

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/neuro-flow#282]
It is rather uneasy to use conditionals in the neuro-flow's job description.

A minimal example to reproduce: 
1. Create job description in `.neuro/live.yaml` file:
```yaml
kind: live
jobs:
  test:
    image: ubuntu
    bash: |
     VAR=qwerty
     if [[ $VAR == "qwerty" ]]; then
      echo yup
     fi
```
2. Try to run it via `neuro-flow run test`
3. Get error
```
ERROR: cannot tokenize data: 7,23: "          if [[ $VAR == "qwerty" ]]; then"
ERROR: Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fc49a267a10>
```

It seems like in case if the parser founds closing literal for the template, but the opening literal was not found previously, it will raise an error.
cc @romasku 

As for me - this logic is more redundant than handy and we could think of removing it.
WDYT, @asvetlov?
