### ISSUE TITLE
Enable bake mode to build images

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/neuro-flow#311]
Actually, this FR contains several requests:
1. Bake description file should be self-contained. We should be able to build images, which are defined in its description. (currently, we could build only images listed in the `live.yaml` file). However, the behavior should echo with a bake behavior - it should build all the images. The command name might be smth like `neuro-flow prepare <batch>`.

2. Add alias command, which will call `neuro-flow prepare <batch>` and `neuro-flow bake <batch>` in a row. For instance, `neuro-flow cook <batch>`.

**Comment by romasku** [comment]
I see the problem, but see some issues with the suggested approach:
- "Batch" mode idea is that you fire command and free to power-off your PC -- bake will continue (except for local actions). So that `cook` command will have to start some "meta-executor" job, that will first build images and the will run normal executor. And if the building of images fails, it will be unclear how to show an error.
- It's not convenient (as for me) to manually select a moment to "build the images". Users can forget to run, or run it more often than required. And then we will end up wanting to add caching here...

I think it's better to solve this using actions:
```
kind: batch
tasks:
  - build_image_1:
    action: gh:neuro-actions/build-image
    args:
      context: storage:path/to/context
      dockerfile: storage:path/to/Dockerfile
      build_args: build_args_here
      env: ${{ to_json({"ENV_1": "foo", "ENV_2": "bar"}) }}
      volumes: ${{ to_json(["storage:volume1", "storage:volume2") }} 
  - real_task:
    image: ${{ needs.build_image_1.image.ref }}
```
Action as above is already possible but has the limitation that context and Dockerfile should be uploaded manually (maybe by some auxiliary local action).

If we add support of local actions inside batch actions (only in case it does not depend directly/indirectly on any remote task), it will be possible to implement the following:
```
kind: batch
tasks:
  - build_image_1:
    action: gh:neuro-actions/build-image
    args:
      context: ${{ flow.workspace / 'path/to/context' }}
      dockerfile: ${{ flow.workspace / 'path/to/context' }}
 ...  # Rest is same as above
```
It will automatically upload data to storage under some semi-random location (inside local action), and then run the remote build step and then return an image ref. It will be able to even utilize ``hash_files`` to avoid unnecessary reuploads and rebuilds.
