### ISSUE TITLE
[FR] upload() command should create partent folders

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/neuro-flow#314]
Neuro-flow in live mode supports auto-uploading of volumes:

```yaml
volumes:
  data:
    remote: storage:data
    mount: /data
    local: data
jobs:
 myjob:
  volumes:
    - ${{ upload(volumes.data).ref_rw }}
```
This job will create a directory for volume itself, but will not create parent folders.
We should adjust it to create parent folders too.
