### ISSUE TITLE
Allow volumes definition in BatchAction

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/neuro-flow#371]
Imagine having a root Batch definition as:
```yaml
kind: batch
...
tasks:
  - id: id1
    bash: echo id1
    image: ubuntu
...
  - id: idN
    needs: [id1]
    action: ws:.neuro/first-level.yaml

```

In such case, the action, defined in `ws:.neuro/first-level.yaml` (which is a sub-DAG actually) is not allowed to contain the definitions of `volumes`, which breaks our understanding of DAG Batch definition.
Why we treat all sub-DAGs as `BatchActions`, but not as `BatchFlow`?

Also, in such BatchActions it is impossible to define the input as a `scalar`, only as mapping, which is also inconsistent.
