### ISSUE TITLE
Empty --param value does not override non-empty default

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/neuro-flow#404]
Example:
```yaml
kind: live
jobs:
  test:
    image: ubuntu
    params:
      p:
        default: "I am a default"
    bash: |
      echo ${{ params.p }}
```

Run with default parameter:
`neuro-flow run test` - parameter has a default value, as expected

Override with some value:
`neuro-flow run test --param p "hey there"` - parameter was overwritten, as expected

Override with empty value:
`neuro-flow run test --param p ""` - default value is used, not as expected, should be ""
