### ISSUE TITLE
Add `git` context to neuro-flow

### ISSUE THREAD

**Issue by anayden** [neuro-inc/neuro-flow#532]
When working with live or batch workflows across multiple branches of same repository it would be very handy to name storage paths and job names according to their git branches, tags or commits.

Consider following live.yaml:

```yaml
id: test

volumes:
  data:
    remote: storage:${{flow.project_id}}/data
    mount: /data
    local: data

jobs:
  train:
    name: train
    volumes:
     - ${{ upload(volumes.data).ref }}
    ...
```

Then consider I run `neuro-flow run train` in `master` and switch to an experiment branch where I make some changes and modify the data. Then I run `neuro-flow run train` from the feature branch and:
- it doesn't work as the job named train already exists and running
- if I overcome this with a multi-job suffix I still overwrite the data for the train job from master and get invalid training results

It would be nice to do something along the lines of:

```yaml
volumes:
  data:
    remote: storage{{flow.project_id}}/${{ git.branch }}/data
    ...

jobs:
  train:
    name: train-${{ git.sha }}
```
