### ISSUE TITLE
Add `local_env` context to neuro-flow

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/neuro-flow#660]
This will allow others to use something like `make` when working with live or batch workflows. 

Consider the following job live.yaml:
```yaml

...
jobs:
  train:
    ...
    prams:
        epochs:
    bash:
       python train.py --epochs ${{ params.epochs }}
```

And makefile:
```make
TRAIN_EPOCHS  ?= 10
train:
    neuro-flow run train --param epochs $(TRAIN_EPOCHS)
```
