### ISSUE TITLE
Support expressions in matrix defenitions

### ISSUE THREAD

**Issue by romasku** [neuro-inc/neuro-flow#682]
It should be possible to use expressions to define matrix products. Such expressions should be limited only to values, that are only available before the bake starts. Syntax should be the following:
```
matrix:
   key: ${{ some_dynamic_list_here }}
```
Also, expressions should be supported for values in include/exclude:
```
matrix:
   k: [1, 2, 3]
   v: [1, 2, 3]
   exclude: 
      - k: 1
         v: ${{ 2 }}
```
and as include/exclude value itself:

```
matrix:
   k: [1, 2, 3]
   v: [1, 2, 3]
   exclude: ${{ [{"k": 1, "v": 2}] }}
```

To make it easy to generate lists, the `range()` function that returns lists that should be added. 
*As sometimes some mapping of values is required, probably we'll have to add comprehensions as in python, but this is under consideration.
