### ISSUE TITLE
Print stdout & stderr messages from local actions

### ISSUE THREAD

**Issue by YevheniiSemendiak** [neuro-inc/neuro-flow#699]
action:
```yaml
kind: local
bash: |
  echo hey stdout >&1
  echo hey stderr >&2
  sleep 300
  exit 1
```
batch:
```yaml
kind: batch
tasks:
  - id: test
    needs: [ ]
    action: ws:.neuro/local.yaml
```

<img width="1214" alt="image" src="https://user-images.githubusercontent.com/32543098/145399900-2e85c644-3934-4e2e-8efb-a56603171711.png">

Problems:
- the user might think the local action is unable to start since the `pending` status only reported
- user is unable to keep track of the local action progress

neuro-flow package version: 21.11.2
