### ISSUE TITLE
Local tasks in live mode

### ISSUE THREAD

**Issue by romasku** [neuro-inc/neuro-flow#742]
### Reasons
Sometimes it can be useful to run some custom logic before starting a job. For example, it can be [interactions with git](https://github.com/neuro-inc/neuro-flow/issues/705), sanity checks, or just accessing [ENV variables](https://github.com/neuro-inc/neuro-flow/issues/660).
### Proposed feature
Let's add `pre` sections to live jobs:
```
develop:
  pre:
    print_hello:
      cmd: /bin/sh -c "echo 'hello world'"
    run_action:
  bash: echo 'Locally printed ${{ pre.print_hello.text }}'
```
It will allow defining a set of commands to run locally. Each entry will specify some program to be executed locally. The console output will be available in expressions as `pre.<pre-name>.text`. The order to run different pre-entries is not specified.

Also, it will be possible to run local actions as pre entries:

```
develop:
  pre:
    run_action:
      action: ws:some-action.yaml
      args:
        some_arg: foo
    run_action:
  bash: echo 'Action returned ${{ pre.run_action.outputs.some_out }}'
```
In this case, arguments will be defined inside pre-entry, and outputs will be accessible in expressions as `pre.<pre-name>.outputs.<output-name>`

Same as with local actions, pre-steps will be only supported for locally defined configs. So actions from GitHub (`gh:` scheme) will be unable to run code on user local machine as it can be a security threat.

Also, pre-steps do not run commands in the shell, they just exec them. This is due to portability (windows shell).

**Comment by romasku** [comment]
Hi everyone, 
@anayden, @YevheniiSemendiak what do you think about this proposal? Will it be useful for you? Or is it overcomplicated? Maybe you see some other use-cases?
@asvetlov please review

**Comment by YevheniiSemendiak** [comment]
Did I get it right, we will not be able to run some script in the `pre` sections, only a single exec is available?

**Comment by romasku** [comment]
> will not be able to run some script in the pre sections

Yes and no. Neuro flow will only single exec. But you can use `/bin/sh -c "some;commands;here"`. But I got your point, and I'm adding `bash` and `python` properties (same as we have for jobs and local actions).

**Comment by romasku** [comment]
> but I imagine ordering of local action is important

Not sure about this. My idea is that this feature should be only for small checks and helpers. If you need some complicated local pipeline, you can just call `make` (or even `neuro-flow bake <some-batch-with-only-local-actions>` from pre-action. 

To make it more specific, we can say that the pre-steps will be executed in the order they are defined in the config file. Though, I would like to see some use-case before defining this (maybe they will show that parallel run is a better option).

As a more exhaustive approach, we can re-use syntax from batch mode:
```
pre:
  - id: step_1
    cmd: do something
  - id: step_2_1
    needs: [step_1]
    cmd: do something else here
  - id: step_2_2
    needs: [ step_1 ]
    cmd: do something else here
  - id: step_3
    needs: [step_2_1, step_2_2]
    cmd: finish here
```
And maybe even add expressions and outputs support, but I personally think it will only make it harder to implement.
